# Example configuration file for TeleMikiya

[telegram]
# Telegram API ID (obtain from https://my.telegram.org)
api_id = 100000
# Telegram API Hash (obtain from https://my.telegram.org)
api_hash = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
# Your Telegram account phone number
phone_number = "+12345678900"
# List of dialog IDs to observe and index messages from
# Leave empty to observe all accessible dialogs
observed_dialog_ids = []
# Dialog info update interval
dialog_update_interval = "24h"
# Telegram Bot Token (obtain from @BotFather)
bot_token = "1234567890:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
# List of Telegram user IDs allowed to use the bot
bot_allowed_user_ids = [123456789]

[database]
# PostgreSQL database host
host = "localhost"
# PostgreSQL database port
port = 5432
# PostgreSQL SSL mode: "disable", "require", "verify-ca", or "verify-full"
ssl_mode = "disable"
# Database connection timeout (optional)
connect_timeout = "1h"
# PostgreSQL database username
user = "telemikiya"
# PostgreSQL database password
password = "telemikiya"
# PostgreSQL database name
db_name = "telemikiya"

# Ollama specific settings
[llm_provider.ollama]
# Ollama API base URL
base_url = "http://localhost:11434"
# Request timeout duration (optional)
timeout = "30s"
# API connection keep-alive duration (optional)
keep_alive = "5m"

# Ollama embedding model settings
[llm_provider.ollama.embedding]
# Embedding model name
model = "snowflake-arctic-embed2:568m"
# Model parameters (optional)
model_parameters = {}
# Embedding vector dimensions
dimensions = 1024

# Ollama image to text model settings
[llm_provider.ollama.image_to_text]
# Image to text model name
model = ""
# Model parameters (optional)
model_parameters = {}

# OpenAI specific settings
[llm_provider.openai]
# OpenAI API base URL (leave empty for default)
base_url = ""
# OpenAI API key
api_key = ""
# Request timeout duration (optional)
timeout = "30s"
# OpenAI organization ID (optional)
organization = ""
# OpenAI project (optional)
project = ""

# OpenAI embedding model settings
[llm_provider.openai.embedding]
# Embedding model name
model = "text-embedding-ada-002"
# Embedding vector dimensions
dimensions = 1536

# OpenAI image to text model settings
[llm_provider.openai.image_to_text]
# Image to text model name
model = ""

# Google specific settings
[llm_provider.google]
# Google API base URL (leave empty for default)
base_url = ""
# Google API key
api_key = ""
# Request timeout duration (optional)
timeout = "30s"
# Google quota project ID (optional)
quota_project = ""

# Google embedding model settings
[llm_provider.google.embedding]
# Embedding model name
model = ""
# Model parameters (optional)
model_parameters = {}
# Embedding vector dimensions
dimensions = 0

# Google image to text model settings
[llm_provider.google.image_to_text]
# Image to text model name
model = ""

[embedding]
# Embedding provider: "ollama", "openai", or "google"
provider = "ollama"
# Batch size (number of messages to process per batch)
batch_size = 10

[image_to_text]
# Image to text provider: "ollama", "openai", or "google"
provider = "ollama"
