// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DialogsColumns holds the columns for the "dialogs" table.
	DialogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"user", "group", "channel"}},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DialogsTable holds the schema information for the "dialogs" table.
	DialogsTable = &schema.Table{
		Name:       "dialogs",
		Columns:    DialogsColumns,
		PrimaryKey: []*schema.Column{DialogsColumns[0]},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "msg_id", Type: field.TypeInt},
		{Name: "text", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "text_embedding", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "vector(%d)"}},
		{Name: "has_media", Type: field.TypeBool},
		{Name: "media_info", Type: field.TypeJSON},
		{Name: "sent_at", Type: field.TypeTime},
		{Name: "dialog_id", Type: field.TypeInt64},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "messages_dialogs_messages",
				Columns:    []*schema.Column{MessagesColumns[7]},
				RefColumns: []*schema.Column{DialogsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "message_msg_id_dialog_id",
				Unique:  true,
				Columns: []*schema.Column{MessagesColumns[1], MessagesColumns[7]},
			},
			{
				Name:    "message_text",
				Unique:  false,
				Columns: []*schema.Column{MessagesColumns[2]},
				Annotation: &entsql.IndexAnnotation{
					Type: "pgroonga",
				},
			},
			{
				Name:    "message_text_embedding",
				Unique:  false,
				Columns: []*schema.Column{MessagesColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					OpClass: "vector_cos_ops",
					Type:    "vectors",
				},
			},
			{
				Name:    "message_sent_at",
				Unique:  false,
				Columns: []*schema.Column{MessagesColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DialogsTable,
		MessagesTable,
	}
)

func init() {
	MessagesTable.ForeignKeys[0].RefTable = DialogsTable
}
