[telegram]
api_id = 0
api_hash = ""
phone_number = ""
observed_dialog_ids = []
dialog_update_interval = "24h"
bot_token = ""
bot_allowed_user_ids = []

[database]
host = "localhost"
port = 5432
ssl_mode = "verify-full"
connect_timeout = 0
user = "telemikiya"
password = ""
db_name = "telemikiya"

[llm_provider.ollama]
base_url = "http://localhost:11434"
timeout = 0
keep_alive = 0

[llm_provider.ollama.embedding]
model = ""
model_parameters = {}
dimensions = 0

[llm_provider.ollama.image_to_text]
model = ""
model_parameters = {}

[llm_provider.openai]
base_url = ""
api_key = ""
timeout = 0
organization = ""
project = ""

[llm_provider.openai.embedding]
model = ""
dimensions = 0

[llm_provider.openai.image_to_text]
model = ""

[llm_provider.google]
base_url = ""
api_key = ""
timeout = 0
quota_project = ""

[llm_provider.google.embedding]
model = ""
dimensions = 0

[llm_provider.google.image_to_text]
model = ""

[embedding]
provider = "ollama"
batch_size = 10

[image_to_text]
provider = "ollama"
