// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	pgvectors "github.com/xyenon/pgvectors-go"
	"github.com/xyenon/telemikiya/database/ent/dialog"
	"github.com/xyenon/telemikiya/database/ent/message"
	"github.com/xyenon/telemikiya/database/ent/predicate"
	"github.com/xyenon/telemikiya/types"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks     []Hook
	mutation  *MessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetMsgID sets the "msg_id" field.
func (mu *MessageUpdate) SetMsgID(i int) *MessageUpdate {
	mu.mutation.ResetMsgID()
	mu.mutation.SetMsgID(i)
	return mu
}

// SetNillableMsgID sets the "msg_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableMsgID(i *int) *MessageUpdate {
	if i != nil {
		mu.SetMsgID(*i)
	}
	return mu
}

// AddMsgID adds i to the "msg_id" field.
func (mu *MessageUpdate) AddMsgID(i int) *MessageUpdate {
	mu.mutation.AddMsgID(i)
	return mu
}

// SetDialogID sets the "dialog_id" field.
func (mu *MessageUpdate) SetDialogID(i int64) *MessageUpdate {
	mu.mutation.SetDialogID(i)
	return mu
}

// SetNillableDialogID sets the "dialog_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableDialogID(i *int64) *MessageUpdate {
	if i != nil {
		mu.SetDialogID(*i)
	}
	return mu
}

// SetText sets the "text" field.
func (mu *MessageUpdate) SetText(s string) *MessageUpdate {
	mu.mutation.SetText(s)
	return mu
}

// SetNillableText sets the "text" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableText(s *string) *MessageUpdate {
	if s != nil {
		mu.SetText(*s)
	}
	return mu
}

// SetTextEmbedding sets the "text_embedding" field.
func (mu *MessageUpdate) SetTextEmbedding(pg pgvectors.Vector) *MessageUpdate {
	mu.mutation.SetTextEmbedding(pg)
	return mu
}

// SetNillableTextEmbedding sets the "text_embedding" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableTextEmbedding(pg *pgvectors.Vector) *MessageUpdate {
	if pg != nil {
		mu.SetTextEmbedding(*pg)
	}
	return mu
}

// ClearTextEmbedding clears the value of the "text_embedding" field.
func (mu *MessageUpdate) ClearTextEmbedding() *MessageUpdate {
	mu.mutation.ClearTextEmbedding()
	return mu
}

// SetHasMedia sets the "has_media" field.
func (mu *MessageUpdate) SetHasMedia(b bool) *MessageUpdate {
	mu.mutation.SetHasMedia(b)
	return mu
}

// SetNillableHasMedia sets the "has_media" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableHasMedia(b *bool) *MessageUpdate {
	if b != nil {
		mu.SetHasMedia(*b)
	}
	return mu
}

// SetMediaInfo sets the "media_info" field.
func (mu *MessageUpdate) SetMediaInfo(ti *types.MediaInfo) *MessageUpdate {
	mu.mutation.SetMediaInfo(ti)
	return mu
}

// SetSentAt sets the "sent_at" field.
func (mu *MessageUpdate) SetSentAt(t time.Time) *MessageUpdate {
	mu.mutation.SetSentAt(t)
	return mu
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableSentAt(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetSentAt(*t)
	}
	return mu
}

// SetDialog sets the "dialog" edge to the Dialog entity.
func (mu *MessageUpdate) SetDialog(d *Dialog) *MessageUpdate {
	return mu.SetDialogID(d.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// ClearDialog clears the "dialog" edge to the Dialog entity.
func (mu *MessageUpdate) ClearDialog() *MessageUpdate {
	mu.mutation.ClearDialog()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if mu.mutation.DialogCleared() && len(mu.mutation.DialogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.dialog"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (mu *MessageUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MessageUpdate {
	mu.modifiers = append(mu.modifiers, modifiers...)
	return mu
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.MsgID(); ok {
		_spec.SetField(message.FieldMsgID, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedMsgID(); ok {
		_spec.AddField(message.FieldMsgID, field.TypeInt, value)
	}
	if value, ok := mu.mutation.Text(); ok {
		_spec.SetField(message.FieldText, field.TypeString, value)
	}
	if value, ok := mu.mutation.TextEmbedding(); ok {
		_spec.SetField(message.FieldTextEmbedding, field.TypeOther, value)
	}
	if mu.mutation.TextEmbeddingCleared() {
		_spec.ClearField(message.FieldTextEmbedding, field.TypeOther)
	}
	if value, ok := mu.mutation.HasMedia(); ok {
		_spec.SetField(message.FieldHasMedia, field.TypeBool, value)
	}
	if value, ok := mu.mutation.MediaInfo(); ok {
		_spec.SetField(message.FieldMediaInfo, field.TypeJSON, value)
	}
	if value, ok := mu.mutation.SentAt(); ok {
		_spec.SetField(message.FieldSentAt, field.TypeTime, value)
	}
	if mu.mutation.DialogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.DialogTable,
			Columns: []string{message.DialogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dialog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.DialogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.DialogTable,
			Columns: []string{message.DialogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dialog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(mu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetMsgID sets the "msg_id" field.
func (muo *MessageUpdateOne) SetMsgID(i int) *MessageUpdateOne {
	muo.mutation.ResetMsgID()
	muo.mutation.SetMsgID(i)
	return muo
}

// SetNillableMsgID sets the "msg_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableMsgID(i *int) *MessageUpdateOne {
	if i != nil {
		muo.SetMsgID(*i)
	}
	return muo
}

// AddMsgID adds i to the "msg_id" field.
func (muo *MessageUpdateOne) AddMsgID(i int) *MessageUpdateOne {
	muo.mutation.AddMsgID(i)
	return muo
}

// SetDialogID sets the "dialog_id" field.
func (muo *MessageUpdateOne) SetDialogID(i int64) *MessageUpdateOne {
	muo.mutation.SetDialogID(i)
	return muo
}

// SetNillableDialogID sets the "dialog_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableDialogID(i *int64) *MessageUpdateOne {
	if i != nil {
		muo.SetDialogID(*i)
	}
	return muo
}

// SetText sets the "text" field.
func (muo *MessageUpdateOne) SetText(s string) *MessageUpdateOne {
	muo.mutation.SetText(s)
	return muo
}

// SetNillableText sets the "text" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableText(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetText(*s)
	}
	return muo
}

// SetTextEmbedding sets the "text_embedding" field.
func (muo *MessageUpdateOne) SetTextEmbedding(pg pgvectors.Vector) *MessageUpdateOne {
	muo.mutation.SetTextEmbedding(pg)
	return muo
}

// SetNillableTextEmbedding sets the "text_embedding" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableTextEmbedding(pg *pgvectors.Vector) *MessageUpdateOne {
	if pg != nil {
		muo.SetTextEmbedding(*pg)
	}
	return muo
}

// ClearTextEmbedding clears the value of the "text_embedding" field.
func (muo *MessageUpdateOne) ClearTextEmbedding() *MessageUpdateOne {
	muo.mutation.ClearTextEmbedding()
	return muo
}

// SetHasMedia sets the "has_media" field.
func (muo *MessageUpdateOne) SetHasMedia(b bool) *MessageUpdateOne {
	muo.mutation.SetHasMedia(b)
	return muo
}

// SetNillableHasMedia sets the "has_media" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableHasMedia(b *bool) *MessageUpdateOne {
	if b != nil {
		muo.SetHasMedia(*b)
	}
	return muo
}

// SetMediaInfo sets the "media_info" field.
func (muo *MessageUpdateOne) SetMediaInfo(ti *types.MediaInfo) *MessageUpdateOne {
	muo.mutation.SetMediaInfo(ti)
	return muo
}

// SetSentAt sets the "sent_at" field.
func (muo *MessageUpdateOne) SetSentAt(t time.Time) *MessageUpdateOne {
	muo.mutation.SetSentAt(t)
	return muo
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableSentAt(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetSentAt(*t)
	}
	return muo
}

// SetDialog sets the "dialog" edge to the Dialog entity.
func (muo *MessageUpdateOne) SetDialog(d *Dialog) *MessageUpdateOne {
	return muo.SetDialogID(d.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// ClearDialog clears the "dialog" edge to the Dialog entity.
func (muo *MessageUpdateOne) ClearDialog() *MessageUpdateOne {
	muo.mutation.ClearDialog()
	return muo
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if muo.mutation.DialogCleared() && len(muo.mutation.DialogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.dialog"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (muo *MessageUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MessageUpdateOne {
	muo.modifiers = append(muo.modifiers, modifiers...)
	return muo
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.MsgID(); ok {
		_spec.SetField(message.FieldMsgID, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedMsgID(); ok {
		_spec.AddField(message.FieldMsgID, field.TypeInt, value)
	}
	if value, ok := muo.mutation.Text(); ok {
		_spec.SetField(message.FieldText, field.TypeString, value)
	}
	if value, ok := muo.mutation.TextEmbedding(); ok {
		_spec.SetField(message.FieldTextEmbedding, field.TypeOther, value)
	}
	if muo.mutation.TextEmbeddingCleared() {
		_spec.ClearField(message.FieldTextEmbedding, field.TypeOther)
	}
	if value, ok := muo.mutation.HasMedia(); ok {
		_spec.SetField(message.FieldHasMedia, field.TypeBool, value)
	}
	if value, ok := muo.mutation.MediaInfo(); ok {
		_spec.SetField(message.FieldMediaInfo, field.TypeJSON, value)
	}
	if value, ok := muo.mutation.SentAt(); ok {
		_spec.SetField(message.FieldSentAt, field.TypeTime, value)
	}
	if muo.mutation.DialogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.DialogTable,
			Columns: []string{message.DialogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dialog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.DialogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.DialogTable,
			Columns: []string{message.DialogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dialog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(muo.modifiers...)
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
