// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/xyenon/telemikiya/database/ent/dialog"
	"github.com/xyenon/telemikiya/database/ent/message"
	"github.com/xyenon/telemikiya/database/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dialogFields := schema.Dialog{}.Fields()
	_ = dialogFields
	// dialogDescUpdatedAt is the schema descriptor for updated_at field.
	dialogDescUpdatedAt := dialogFields[3].Descriptor()
	// dialog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dialog.DefaultUpdatedAt = dialogDescUpdatedAt.Default.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
}
