// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Dialog is the predicate function for dialog builders.
type Dialog func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)
